import io
from datetime import datetime
from zoneinfo import ZoneInfo

import qrcode

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    Image,
    HRFlowable,
)
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle,
)

from agents.brand import (
    BRAND_NAME,
    BRAND_TAGLINE,
    COLOR_PRIMARY,
    COLOR_ACCENT,
    COLOR_DARK,
    COLOR_MUTED,
    COLOR_BG_STRIP,
    HEX_MUTED,
    HEX_ACCENT,
    draw_logo,
)

from schemas import InvoiceRequest


"""
Produces the actual formatted AyurHerb invoice PDF.

Important responsibility split:

- Financial figures come directly from InvoiceRequest.
- Transaction date/time comes directly from transactionAt.
- QR code is generated from the supplied verification URL.
- The LLM only supplies the short invoice note.
- No financial amount, transaction timestamp, or verification
  information is generated by the LLM.
"""


# ============================================================
# STYLES
# ============================================================

styles = getSampleStyleSheet()


style_body = ParagraphStyle(
    "body",
    parent=styles["Normal"],
    fontName="Helvetica",
    fontSize=9.5,
    textColor=COLOR_DARK,
    leading=13,
)


style_label = ParagraphStyle(
    "label",
    parent=styles["Normal"],
    fontName="Helvetica-Bold",
    fontSize=8,
    textColor=COLOR_MUTED,
    leading=11,
)


style_notes = ParagraphStyle(
    "notes",
    parent=styles["Normal"],
    fontName="Helvetica-Oblique",
    fontSize=8.5,
    textColor=COLOR_MUTED,
    leading=12,
)


# ============================================================
# DATE / TIME FORMATTER
# ============================================================

def _format_transaction_datetime(
    transaction_at: datetime | None,
) -> tuple[str, str]:
    """
    Convert the canonical transaction timestamp into
    human-readable Indian date and time.

    Example:

        09 September 2026
        08:58 PM IST

    The backend sends the timestamp as the actual payment /
    escrow funding timestamp.
    """

    if not transaction_at:
        return "N/A", "N/A"

    try:
        # If the datetime has no timezone, treat it as UTC
        # because Node sends the timestamp in ISO/UTC form.
        if transaction_at.tzinfo is None:
            transaction_at = transaction_at.replace(
                tzinfo=ZoneInfo("UTC")
            )

        india_time = transaction_at.astimezone(
            ZoneInfo("Asia/Kolkata")
        )

        date_text = india_time.strftime(
            "%d %B %Y"
        )

        time_text = india_time.strftime(
            "%I:%M %p IST"
        )

        return date_text, time_text

    except Exception:
        return "N/A", "N/A"


# ============================================================
# QR CODE
# ============================================================

def _make_qr_flowable(
    verify_url: str,
    size_mm: float = 28,
) -> Image:

    qr = qrcode.QRCode(
        border=1,
        box_size=8,
    )

    qr.add_data(verify_url)
    qr.make(fit=True)

    img = qr.make_image(
        fill_color="#12241A",
        back_color="white",
    )

    buf = io.BytesIO()

    img.save(
        buf,
        format="PNG",
    )

    buf.seek(0)

    return Image(
        buf,
        width=size_mm * mm,
        height=size_mm * mm,
    )


# ============================================================
# LETTERHEAD
# ============================================================

def _letterhead(
    invoice_number: str,
    order_id: str,
) -> list:

    logo_drawing = draw_logo(
        0,
        0,
        size=30,
    )

    header_table = Table(
        [
            [
                logo_drawing,
                Paragraph(
                    f'<font size="7" color="{HEX_MUTED}">'
                    f'INVOICE #{invoice_number}<br/>'
                    f'Order ref: {order_id}'
                    f'</font>',
                    style_body,
                ),
            ]
        ],
        colWidths=[
            90 * mm,
            80 * mm,
        ],
    )

    header_table.setStyle(
        TableStyle(
            [
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "ALIGN",
                    (1, 0),
                    (1, 0),
                    "RIGHT",
                ),
            ]
        )
    )

    tagline = Paragraph(
        f'<font size="8" color="{HEX_ACCENT}">'
        f'<i>{BRAND_TAGLINE}</i>'
        f'</font>',
        style_body,
    )

    return [
        header_table,
        Spacer(1, 2 * mm),
        tagline,
        Spacer(1, 3 * mm),
        HRFlowable(
            width="100%",
            thickness=1.2,
            color=COLOR_PRIMARY,
        ),
        Spacer(1, 5 * mm),
    ]


# ============================================================
# TRANSACTION INFORMATION
# ============================================================

def _transaction_block(
    req: InvoiceRequest,
) -> Table:

    transaction_date, transaction_time = (
        _format_transaction_datetime(
            req.transactionAt
        )
    )

    data = [
        [
            Paragraph(
                "TRANSACTION DATE",
                style_label,
            ),
            Paragraph(
                "TRANSACTION TIME",
                style_label,
            ),
            Paragraph(
                "INVOICE GENERATED",
                style_label,
            ),
        ],
        [
            Paragraph(
                f"<b>{transaction_date}</b>",
                style_body,
            ),
            Paragraph(
                f"<b>{transaction_time}</b>",
                style_body,
            ),
            Paragraph(
                f"{_format_generated_datetime(req)}",
                style_body,
            ),
        ],
    ]

    table = Table(
        data,
        colWidths=[
            56 * mm,
            56 * mm,
            58 * mm,
        ],
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    COLOR_BG_STRIP,
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.5,
                    COLOR_MUTED,
                ),
                (
                    "INNERGRID",
                    (0, 0),
                    (-1, -1),
                    0.35,
                    COLOR_MUTED,
                ),
            ]
        )
    )

    return table


def _format_generated_datetime(
    req: InvoiceRequest,
) -> str:

    """
    InvoiceRequest currently does not necessarily contain an
    invoice generated timestamp.

    The invoice generator itself does not need to expose this
    separately. If unavailable, simply display N/A.
    """

    generated_at = getattr(
        req,
        "generatedAt",
        None,
    )

    if not generated_at:
        return "N/A"

    date_text, time_text = (
        _format_transaction_datetime(
            generated_at
        )
    )

    return f"{date_text}<br/>{time_text}"


# ============================================================
# PARTY BLOCK
# ============================================================

def _party_block(
    req: InvoiceRequest,
) -> Table:

    data = [
        [
            Paragraph(
                "BILL TO (COMPANY)",
                style_label,
            ),
            Paragraph(
                "SHIP FROM (FARMER)",
                style_label,
            ),
        ],
        [
            Paragraph(
                f"<b>{req.companyName}</b><br/>"
                f"GSTIN: {req.companyGstNumber}",
                style_body,
            ),
            Paragraph(
                f"<b>{req.farmerName}</b><br/>"
                f"{req.farmerLocation}",
                style_body,
            ),
        ],
    ]

    table = Table(
        data,
        colWidths=[
            85 * mm,
            85 * mm,
        ],
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, 0),
                    4,
                ),
                (
                    "TOPPADDING",
                    (0, 1),
                    (-1, 1),
                    2,
                ),
            ]
        )
    )

    return table


# ============================================================
# LINE ITEMS
# ============================================================

def _line_items_table(
    req: InvoiceRequest,
) -> Table:

    """
    Crop line item only.

    Raw agricultural produce is kept separate from the
    taxable service fees.
    """

    header = [
        "Description",
        "Quantity",
        "Unit Price (INR)",
        "Amount (INR)",
    ]

    unit_price = (
        req.cropSubtotal / req.quantity
        if req.quantity
        else 0
    )

    row = [
        (
            f"{req.cropName} "
            "(raw agricultural produce — GST exempt)"
        ),
        f"{req.quantity:,.2f} {req.unit}",
        f"{unit_price:,.2f}",
        f"{req.cropSubtotal:,.2f}",
    ]

    table = Table(
        [header, row],
        colWidths=[
            65 * mm,
            30 * mm,
            40 * mm,
            35 * mm,
        ],
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    COLOR_PRIMARY,
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.white,
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),
                (
                    "FONTSIZE",
                    (0, 0),
                    (-1, -1),
                    9,
                ),
                (
                    "ALIGN",
                    (1, 0),
                    (-1, -1),
                    "RIGHT",
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
            ]
        )
    )

    return table


# ============================================================
# CHARGES
# ============================================================

def _charges_table(
    req: InvoiceRequest,
) -> Table:

    data = [
        [
            "Charges",
            "",
            "Amount (INR)",
        ],
        [
            "Crop subtotal (GST exempt)",
            "",
            f"{req.cropSubtotal:,.2f}",
        ],
        [
            (
                f"Platform service fee "
                f"({req.platformFeePercent:.1f}%)"
            ),
            "",
            f"{req.platformFeeAmount:,.2f}",
        ],
        [
            "Transportation & logistics fee",
            "",
            f"{req.transportationFeeAmount:,.2f}",
        ],
        [
            (
                f"GST on fees "
                f"({req.gstOnFeesPercent:.0f}%)"
            ),
            "",
            f"{req.gstOnFeesAmount:,.2f}",
        ],
        [
            "Grand Total (Payable by Company)",
            "",
            f"INR {req.grandTotal:,.2f}",
        ],
    ]

    table = Table(
        data,
        colWidths=[
            95 * mm,
            20 * mm,
            55 * mm,
        ],
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    COLOR_BG_STRIP,
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),
                (
                    "FONTSIZE",
                    (0, 0),
                    (-1, -1),
                    9,
                ),
                (
                    "ALIGN",
                    (2, 0),
                    (2, -1),
                    "RIGHT",
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
                (
                    "LINEABOVE",
                    (0, -1),
                    (-1, -1),
                    0.75,
                    COLOR_PRIMARY,
                ),
                (
                    "FONTNAME",
                    (0, -1),
                    (-1, -1),
                    "Helvetica-Bold",
                ),
                (
                    "FONTSIZE",
                    (0, -1),
                    (-1, -1),
                    10.5,
                ),
                (
                    "TEXTCOLOR",
                    (0, -1),
                    (-1, -1),
                    COLOR_PRIMARY,
                ),
                (
                    "TOPPADDING",
                    (0, -1),
                    (-1, -1),
                    8,
                ),
            ]
        )
    )

    return table


# ============================================================
# ESCROW TERMS
# ============================================================

def _payment_terms_table(
    req: InvoiceRequest,
) -> Table:

    shipment_amt = (
        req.cropSubtotal
        * req.shipmentTranchePercent
        / 100
    )

    delivery_amt = (
        req.cropSubtotal
        * req.deliveryTranchePercent
        / 100
    )

    data = [
        [
            "Milestone (Farmer Payout)",
            "Release %",
            "Amount (INR)",
        ],
        [
            "On shipment start",
            f"{req.shipmentTranchePercent}%",
            f"{shipment_amt:,.2f}",
        ],
        [
            "On confirmed delivery",
            f"{req.deliveryTranchePercent}%",
            f"{delivery_amt:,.2f}",
        ],
        [
            "Total to farmer",
            "100%",
            f"{req.cropSubtotal:,.2f}",
        ],
    ]

    table = Table(
        data,
        colWidths=[
            70 * mm,
            35 * mm,
            40 * mm,
        ],
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    COLOR_BG_STRIP,
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    COLOR_DARK,
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),
                (
                    "FONTSIZE",
                    (0, 0),
                    (-1, -1),
                    8.5,
                ),
                (
                    "ALIGN",
                    (1, 0),
                    (-1, -1),
                    "RIGHT",
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
                (
                    "LINEBELOW",
                    (0, 0),
                    (-1, 0),
                    0.5,
                    COLOR_MUTED,
                ),
                (
                    "LINEABOVE",
                    (0, -1),
                    (-1, -1),
                    0.5,
                    COLOR_MUTED,
                ),
                (
                    "FONTNAME",
                    (0, -1),
                    (-1, -1),
                    "Helvetica-Bold",
                ),
            ]
        )
    )

    return table


# ============================================================
# BUILD PDF
# ============================================================

def build_invoice_pdf(
    req: InvoiceRequest,
    invoice_notes: str,
    verify_url: str,
) -> bytes:

    buf = io.BytesIO()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
    )

    story = []

    # --------------------------------------------------------
    # LETTERHEAD
    # --------------------------------------------------------

    story += _letterhead(
        req.invoiceNumber,
        req.orderId,
    )

    # --------------------------------------------------------
    # TRANSACTION DATE / TIME
    # --------------------------------------------------------

    story.append(
        Paragraph(
            "TRANSACTION INFORMATION",
            style_label,
        )
    )

    story.append(
        Spacer(1, 2 * mm)
    )

    story.append(
        _transaction_block(req)
    )

    story.append(
        Spacer(1, 7 * mm)
    )

    # --------------------------------------------------------
    # BUYER / SELLER
    # --------------------------------------------------------

    story.append(
        _party_block(req)
    )

    story.append(
        Spacer(1, 8 * mm)
    )

    # --------------------------------------------------------
    # ORDER DETAILS
    # --------------------------------------------------------

    story.append(
        Paragraph(
            "ORDER DETAILS",
            style_label,
        )
    )

    story.append(
        Spacer(1, 2 * mm)
    )

    story.append(
        _line_items_table(req)
    )

    story.append(
        Spacer(1, 8 * mm)
    )

    # --------------------------------------------------------
    # PAYMENT
    # --------------------------------------------------------

    story.append(
        Paragraph(
            "PAYMENT DUE FROM COMPANY",
            style_label,
        )
    )

    story.append(
        Spacer(1, 2 * mm)
    )

    story.append(
        _charges_table(req)
    )

    story.append(
        Spacer(1, 8 * mm)
    )

    # --------------------------------------------------------
    # ESCROW TERMS
    # --------------------------------------------------------

    story.append(
        Paragraph(
            "ESCROW RELEASE TERMS",
            style_label,
        )
    )

    story.append(
        Spacer(1, 2 * mm)
    )

    story.append(
        _payment_terms_table(req)
    )

    story.append(
        Spacer(1, 8 * mm)
    )

    # --------------------------------------------------------
    # NOTES
    # --------------------------------------------------------

    if invoice_notes:

        story.append(
            Paragraph(
                "NOTES",
                style_label,
            )
        )

        story.append(
            Spacer(1, 1.5 * mm)
        )

        story.append(
            Paragraph(
                invoice_notes,
                style_notes,
            )
        )

        story.append(
            Spacer(1, 8 * mm)
        )

    # --------------------------------------------------------
    # QR VERIFICATION
    # --------------------------------------------------------

    qr_table = Table(
        [
            [
                _make_qr_flowable(
                    verify_url
                ),
                Paragraph(
                    f'<font size="8" color="{HEX_MUTED}">'
                    f"<b>Scan to verify</b><br/>"
                    f"This QR code opens the public "
                    f"AyurHerb verification record for "
                    f"this order's crop provenance, "
                    f"invoice details and blockchain proof."
                    f"<br/><br/>"
                    f"Farmers: print this code on shipment packs."
                    f"</font>",
                    style_body,
                ),
            ]
        ],
        colWidths=[
            30 * mm,
            130 * mm,
        ],
    )

    qr_table.setStyle(
        TableStyle(
            [
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
            ]
        )
    )

    story.append(
        qr_table
    )

    # --------------------------------------------------------
    # FOOTER
    # --------------------------------------------------------

    story.append(
        Spacer(1, 10 * mm)
    )

    story.append(
        HRFlowable(
            width="100%",
            thickness=0.5,
            color=COLOR_ACCENT,
        )
    )

    story.append(
        Spacer(1, 2 * mm)
    )

    story.append(
        Paragraph(
            f'<font size="7" color="{HEX_MUTED}">'
            f"Generated by {BRAND_NAME} — funds held in "
            f"platform escrow (Razorpay, test mode) until "
            f"milestone release, verified on-chain."
            f"</font>",
            style_body,
        )
    )

    # --------------------------------------------------------
    # BUILD
    # --------------------------------------------------------

    doc.build(story)

    buf.seek(0)

    return buf.read()